### PR TITLE
improve error message

### PR DESCRIPTION
**Pull request by jack99999**
fixed 'Occured' typo. Improved text of message.

### CODE REVIEW

**Comment by milouse** [comment]
Thank you very much!

**Comment by jack99999** [comment]
i am working my way through DOCUMENTATION.org at the moment... question:

found these:

#+begin_note
The default ~author~ setting is inferred from your user name on your
current computer system session.
#+end_note

inferred?


#+begin_note
The default ~lang~ setting is inferred from your current system one.
#+end_note


what do you mean by 'inferred' here. i assume you mean 'is the same as',
but maybe there is more to it?


thanks

jack
I've always lived my life sideways. It's the best way of avoiding what
lies ahead.

**Comment by milouse** [comment]
It’s the verb [infer](https://www.oxfordlearnersdictionaries.com/definition/english/infer?q=infer), like *deducted*… I agree it’s not the best verb for the first case, and it should be written like the following, as it is taken « as this »

> The default `author` setting is taken from your user name on your…

But for the lang, it’s more indirect. Thus I take infer as it’s like « inférer » in french (I’m french). But you’re right that maybe « deduced » is simpler?

**Comment by jack99999** [comment]
yes, i thought of 'taken' after i sent the mail. that's much clearer.

fwiw, people often get confused between imply and infer. nobody has
trouble with 'taken'!

i'll change it to 'taken' (tomorrow).


another question. i found:

- source :: [string, optional] this option is incompatible with the
   ~content~: either you have a ~content~ or a ~source~, never both of
   them. The aim of this option is to target, with a CSS selector, any
   part of the HTML document, in order to move it elsewhere. See example
   below.


   ...but the description of 'content' does not have the same
restriction mentioned. i assume i need to add it?


and last question:

The ~templates~ option stores an array of /template/, each one
documenting an HTML fragment to insert or move at some place in a
specified generated file. Each template listed in that array is an
object, which must use the following keys:


i don't understand that 'or move'  (and there are some more in the
explanation).
can you explain what happens with move?


thanks


jack
Keep your feet to the grindstone

**Comment by jack99999** [comment]
forgot to say, don't accept that pull request, i'll fix 'taken' tomorrow
and amend the request.

also, will make other changes depending on your reply to my previous mail.


cheers


jack
Compact yet vigorous hybrid bush pumpkin. An abundant cropper.

**Pull request merged**
