### PR TITLE
documentation tidy

### PR DESCRIPTION
**Pull request by jack99999**
quick pass to fix typos, some wording changes.

### CODE REVIEW

**Comment by milouse** [comment]
Hi again,

I switch to this PR to discuss your previous questions on #1 as I closed it too quickly :/

> yes, i thought of 'taken' after i sent the mail. that's much clearer. fwiw, people often get confused between imply and infer. nobody has trouble with 'taken'! i'll change it to 'taken' (tomorrow).

Good idea :)

> Another question. i found: `- source :: [string, optional] this option is incompatible with the ~content~: either you have a ~content~ or a ~source~, never both of them. The aim of this option is to target, with a CSS selector, any part of the HTML document, in order to move it elsewhere. See example below.` ...but the description of `content` does not have the same restriction mentioned. I assume I need to add it? 

Effectivelly it may be better to add it. When I wrote it, I thought that `source` will be used far less than the `content` option, and thus we don’t need to precise it for the `content` option (to avoid confusing the end-user with something they won't use anyway). However you are right it will be more clear if the two options clearly state this incompatibility.

> and last question: `The ~templates~ option stores an array of /template/, each one documenting an HTML fragment to insert or move at some place in a specified generated file. Each template listed in that array is an object, which must use the following keys`: i don't understand that 'or move'  (and there are some more in the explanation). can you explain what happens with move?

The aim of the `move` option is to move some parts of the final document inside the document. For exemple, by default, the Org HTML export set the table of content **inside** the same HTML `div` element than the content of the document. One may want to put the table of content in its own HTML `div`, or maybe move it to the end of the document (after the content). This option enable you to select the DOM element you want to move (described by the `source` option) and its destination (described by the `selector` option). Is it more clear?

Thank you very much for you help!

**Comment by jack99999** [comment]
ah, yes, that explanation of move makes sense. that's ok then.

i don't think i've got anything left to do, but if i've got something wrong somewhere i'm sure you'll let me know.

thanks

**Comment by milouse** [comment]
Thank you very much for you help. All of this has been merged as part of 3e458de

**Comment by jack99999** [comment]
get back to me if you ever want me to look at anything else.

jack

**Pull request closed without merging**
